# Generated by Django 5.1.7 on 2025-03-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
