# Generated by Django 5.1.7 on 2025-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_auth', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
